# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


app_name = 'dj_proposals_candidates'
urlpatterns = [
    url(
        regex="^Candidate/~create/$",
        view=views.CandidateCreateView.as_view(),
        name='Candidate_create',
    ),
    url(
        regex="^Candidate/(?P<pk>\d+)/~delete/$",
        view=views.CandidateDeleteView.as_view(),
        name='Candidate_delete',
    ),
    url(
        regex="^Candidate/(?P<pk>\d+)/$",
        view=views.CandidateDetailView.as_view(),
        name='Candidate_detail',
    ),
    url(
        regex="^Candidate/(?P<pk>\d+)/~update/$",
        view=views.CandidateUpdateView.as_view(),
        name='Candidate_update',
    ),
    url(
        regex="^Candidate/$",
        view=views.CandidateListView.as_view(),
        name='Candidate_list',
    ),
	url(
        regex="^Proposal/~create/$",
        view=views.ProposalCreateView.as_view(),
        name='Proposal_create',
    ),
    url(
        regex="^Proposal/(?P<pk>\d+)/~delete/$",
        view=views.ProposalDeleteView.as_view(),
        name='Proposal_delete',
    ),
    url(
        regex="^Proposal/(?P<pk>\d+)/$",
        view=views.ProposalDetailView.as_view(),
        name='Proposal_detail',
    ),
    url(
        regex="^Proposal/(?P<pk>\d+)/~update/$",
        view=views.ProposalUpdateView.as_view(),
        name='Proposal_update',
    ),
    url(
        regex="^Proposal/$",
        view=views.ProposalListView.as_view(),
        name='Proposal_list',
    ),
	url(
        regex="^Commitment/~create/$",
        view=views.CommitmentCreateView.as_view(),
        name='Commitment_create',
    ),
    url(
        regex="^Commitment/(?P<pk>\d+)/~delete/$",
        view=views.CommitmentDeleteView.as_view(),
        name='Commitment_delete',
    ),
    url(
        regex="^Commitment/(?P<pk>\d+)/$",
        view=views.CommitmentDetailView.as_view(),
        name='Commitment_detail',
    ),
    url(
        regex="^Commitment/(?P<pk>\d+)/~update/$",
        view=views.CommitmentUpdateView.as_view(),
        name='Commitment_update',
    ),
    url(
        regex="^Commitment/$",
        view=views.CommitmentListView.as_view(),
        name='Commitment_list',
    ),
	url(
        regex="^Party/~create/$",
        view=views.PartyCreateView.as_view(),
        name='Party_create',
    ),
    url(
        regex="^Party/(?P<pk>\d+)/~delete/$",
        view=views.PartyDeleteView.as_view(),
        name='Party_delete',
    ),
    url(
        regex="^Party/(?P<pk>\d+)/$",
        view=views.PartyDetailView.as_view(),
        name='Party_detail',
    ),
    url(
        regex="^Party/(?P<pk>\d+)/~update/$",
        view=views.PartyUpdateView.as_view(),
        name='Party_update',
    ),
    url(
        regex="^Party/$",
        view=views.PartyListView.as_view(),
        name='Party_list',
    ),
	url(
        regex="^Coalition/~create/$",
        view=views.CoalitionCreateView.as_view(),
        name='Coalition_create',
    ),
    url(
        regex="^Coalition/(?P<pk>\d+)/~delete/$",
        view=views.CoalitionDeleteView.as_view(),
        name='Coalition_delete',
    ),
    url(
        regex="^Coalition/(?P<pk>\d+)/$",
        view=views.CoalitionDetailView.as_view(),
        name='Coalition_detail',
    ),
    url(
        regex="^Coalition/(?P<pk>\d+)/~update/$",
        view=views.CoalitionUpdateView.as_view(),
        name='Coalition_update',
    ),
    url(
        regex="^Coalition/$",
        view=views.CoalitionListView.as_view(),
        name='Coalition_list',
    ),
	]
